#  Description: Configuration file for the project
DEFAULT_SPEED = 5
DEFAULT_ORAL = 2
DEFAULT_LAUGH = 0
DEFAULT_BK = 4
# 段落切割
DEFAULT_SEG_LENGTH = 120
DEFAULT_BATCH_SIZE = 5
# 温度
DEFAULT_TEMPERATURE = 0.3
# top_P
DEFAULT_TOP_P = 0.7
# top_K
DEFAULT_TOP_K = 20
